apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 3
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app-container
          image: gcr.io/sincere-hearth-377212/mydocker-image
          ports:
            - containerPort: 8000
        - name: redis-container
          image: redis
          ports:
            - containerPort: 6379
  selector:
    matchLabels:
      app: demo-app
